version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=meetapp
      - POSTGRES_DB=MeetApp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  app:
    container_name: MeetApp
    build: .
    ports:
      - '3333:3333'
    command: yarn dev
    environment:
      - DB_HOST=postgres
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USER=
      - MAIL_PASS=
    volumes:
      - '.:/usr/app'

  queue:
    container_name: Queue
    build: .
    command: yarn queue
    environment:
      - DB_HOST=postgres
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USER=
      - MAIL_PASS=
    volumes:
      - '.:/usr/app'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  postgres_data:
